source 'http://ruby.taobao.org'

gem 'rails', '~> 3.2.8'
gem 'e_rails', :git => 'git://github.com/eDoctor/eRails.git'
gem 'slim-rails'

group :assets do
  gem 'compass-rails'
  gem 'sass-rails'
end

########## ☟ Sort by letter ☟ ##########
# gem 'capistrano'
# gem 'mongoid'
# gem 'mysql2'
# gem 'rails_emoji'
# gem 'rails_kindeditor'
