source 'http://ruby.taobao.org'

gem 'rails', '~> 3.2.6'
gem 'slim-rails'
gem 'e_rails', :git => 'git://github.com/eDoctor/eRails.git'

group :assets do
  gem 'compass-rails'
  # gem 'oily_png' # 为 Compass 加速图片拼接
  gem 'sass-rails'
end

########## ☟ Sort by letter ☟ ##########

# gem 'capistrano' # Deploy
# gem 'json'
# gem 'mongoid', '~> 3.0.0'
# gem 'mysql2'
# gem 'rails_emoji', '~> 1.6.0'
# gem 'rails_kindeditor', '~> 0.3.0'
