source 'http://ruby.taobao.org'

gem 'rails'
gem 'slim-rails'

## Sort by letter
gem 'json'
gem 'mysql2'
# gem 'rails_kindeditor', '~> 0.3.0'

## Gems used only for assets and not required in production environments by default.
group :assets do
  gem 'compass-rails'
  # gem 'oily_png'      # 为Compass加速PNG拼接
  gem 'sass-rails'
  gem 'therubyracer'  # 为Ruby嵌入V8引擎
  gem 'uglifier'      # 压缩
end

## Deploy with Capistrano
gem 'capistrano'

gem 'e_rails', :path => 'eRails'
